# Base configuration for all environments
app:
  name: "Niney Life Pickr"
  version: "1.0.0"
  description: "Life decision picker app"

server:
  host: "localhost"
  port: 3000
  strictPort: true # Must use this exact port
  # Friendly server (Node.js backend)
  friendly:
    host: "localhost"
    port: 4000
    cors:
      origin: "http://localhost:3000"
  # Smart server (Python backend) - Future
  smart:
    host: "localhost"
    port: 5000

vite:
  clearScreen: true
  logLevel: "info"

pwa:
  enabled: true
  registerType: "autoUpdate"

api:
  timeout: 30000
  retries: 3
