# Production-specific configuration
# Inherits from base.yml and overrides specific values

server:
  web:
    host: "0.0.0.0"  # Allow external connections
    port: 3000
  friendly:
    host: "0.0.0.0"
    port: 4000
    cors:
      origin: "https://niney-life-pickr.com"  # Production domain
    logLevel: "error"  # Production should only log errors
  smart:
    host: "0.0.0.0"
    port: 5000

vite:
  clearScreen: false
  logLevel: "error"

build:
  minify: true
  sourcemap: false
  chunkSizeWarningLimit: 1000

pwa:
  enabled: true
  registerType: "prompt"  # Ask user before updating in production

api:
  url: "https://nlpfriendly.easypcb.co.kr"  # Web용 Production API URL
  timeout: 60000
  retries: 5
  # Mobile 플랫폼별 API URL (Production)
  mobile:
    android: "https://nlpfriendly.easypcb.co.kr"  # Android
    ios: "https://nlpfriendly.easypcb.co.kr"      # iOS

performance:
  preload: true
  prefetch: true
  compression: true
